# Use a imagem do SDK do .NET 8 para construir a aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY . ./

# Publique a aplicação em modo de release
RUN dotnet publish -c Release -o out

# Use a imagem do runtime do .NET 8 para executar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copie a saída da construção para o contêiner
COPY --from=build-env /app/out .

# Defina a variável de ambiente para produção
ENV ASPNETCORE_ENVIRONMENT Production

# Defina o ponto de entrada da aplicação
ENTRYPOINT ["dotnet", "GitHub_Old_Repos.dll"]
